print('*****DESAFIO 02*****')
print('\nCrie um script em Python que leia o dia, o mês e o ano de nascimento de uma pessoa e mostre uma mensagem com a data formatada.')
dia = input('\nDigite o dia do seu nascimento: ')
mes = input('Digite o mês do seu nascimento: ')
ano = input('Digite o ano do seu nascimento: ')
print('\nVocê nasceu no dia:',dia,'no mês de:',mes,'no ano de:',ano,'Certo?')
